### ISSUE TITLE
no "new project" dialog

### ISSUE THREAD

**Issue by sphaero** [praxis-live/support#100]
On Debian Buster no dialog appears when clicking "New Project"

On startup this warning is generated:
```
$ _JAVA_OPTIONS="" ./praxis_live
Picked up _JAVA_OPTIONS: 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.netbeans.ProxyURLStreamHandlerFactory (file:/home/arnaud/Downloads/praxis_live/platform/lib/boot.jar) to field java.net.URL.handler
WARNING: Please consider reporting this to the maintainers of org.netbeans.ProxyURLStreamHandlerFactory
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
Apart from that no other messages

**Comment by neilcsmith-net** [comment]
Thanks. Sorry about that. PraxisLIVE currently requires OpenJDK 8. Please set up java and javac via update alternatives, or you can use the --jdkhome flag. There are a few dependencies that have issues with Java 9+ but should be fixed soon.

**Comment by sphaero** [comment]
Ah thanks, didn't notice that. It works now
