### ISSUE TITLE
Review container API

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#11]
In my opinion if a property is in a container it should be a `core:container:property` automatically. Similar confusion with `core:video:output` and `core:video:container:output` .

**Comment by neilcsmith-net** [comment]
As I may have mentioned by email, the container API has not been updated during development of Praxis LIVE v2.  In it's current state it should probably be considered semi-deprecated - which is not to say I think it should be removed, but that some of the reasons for it existing have been replaced by the new custom code support.  It needs a good rethink!

`core:property` and `core:container:property` do have quite different behaviour, and the behaviour of the latter cannot be replicated within the new coding API.  There are also reasons you might want a `core:property` to be hidden at the level above.  I'd rather get rid of `core:container:property` entirely.  My thoughts are around instead adding the ability to proxy any control from a child on to the parent container.  How does that sound?

I'm less sure what to do about ports.  `video:output` and `video:container:output` are very different.  None of the properties for `video:output` around window sizing, rotation, titling, etc. make sense in a container.  Again, it might make sense for ports to be defined on the container itself.

Finally, I'm wondering about adding `video:container` and `audio:container` - the former allowing a graph to work on a region of the parent image, the latter possibly allowing an audio graph to work at an alternative block size to the parent.

Please add your thoughts to this (meta) issue and use it as a platform for discussion.  We can pull out individual issues from this as necessary.

Thanks!

**Comment by maxdee** [comment]
I understand the differences between these components. Its confusion at a user level. Perhaps just changing names, something like "inlet" "outlet" like in PD. This would be clearer. 
As for proxying controls on to the parent container, would that mean any control (define control?) within the container would be visible on the container component?
Also color coding components could be nice...

**Comment by neilcsmith-net** [comment]
As per private email - controls as in everything that shows up when you double-click on a component (properties and actions primarily).  http://praxis-live.readthedocs.org/en/latest/architecture/#ports-controls 

Or, deprecate `core:container:property` and remove all ability to add controls to containers entirely?  Could possibly add something similar to Pure Data's graph-on-parent functionality in the editor.  OTOH, if they're not real controls, there's nothing on the container to bind MIDI events or GUI components to - you'd have to bind to the components inside the container instead.

Please open another issue on colour coding - agree it would be nice!

**Comment by neilcsmith-net** [comment]
Going to punt this to v3, which I'm aiming for mid-2016. That way there's more scope for deprecating / replacing aspects of this.

**Comment by neilcsmith-net** [comment]
`core:container:property` is now deprecated. Input and Output ports are renamed eg. `core:container:in`, `video:container:out`. This is so the default names match usual port names - hopefully less confusing now.

Graph on parent functionality isn't included as yet - this may come later. Or, as it's no longer possible to create controls on containers anyway, maybe the default double-click action should be to open them?
