### ISSUE TITLE
Support OSC wildcards

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#115]
It would be fun if Praxis Live supported OSC wildcards. One could have a patch with multiple components with a speed parameter, using `/video/*/speed 0.3` would control all the speeds without having to manually connect them which would also reduce the mess of cords.

Supporting other OSC address matching feature could be nice also, but I could do without those.
[http://opensoundcontrol.org/spec-1_0](http://opensoundcontrol.org/spec-1_0)

**Comment by neilcsmith-net** [comment]
This one is unfortunately difficult at the moment. It would involve changing the underlying actor messaging to support wildcards as well, which may not be feasible. The OSC nodes have no idea of the topology of the actor tree.

If you override the default OSC address, you can have multiple mappings from one OSC address so a single message can control multiple things.  If we can add a better UI for mapping OSC (as per #116 ) that might actually support this better.

Or in a component one other option besides patching directly is `transmit()`

ie. have a single controller node and use

```
@P(1)
    @Type.Number(min = 0, max = 1, def = 0.5)
    Property speed;
    
    @Override
    public void init() {
        speed.link(s -> {
            transmit("p2d-1", "speed", s);
            transmit("p2d-2", "speed", s);
        });
    }
```

At the moment you can't get direct access to the parent container - I'm planning on adding that, which means you could also loop through all components looking for those with a speed port.

And, maybe not so relevant, but remember that the keyboard controls on the graph do support wildcards.

**Comment by maxdee** [comment]
Clever I did not think of that. Maybe I will implement it in my OSC root generator :)
