### ISSUE TITLE
Automaticaly add OSC inputs for all components

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#116]
I think I may have brought this up before. It would be really nice if OSC roots had a checkbox for automatically adding all praxis control addresses. I had made a processing sketch to do this but found myself having to debug it during a gig which was not fun (due to a PXG format update?). 

A simple checkbox would be nice and effective. Also if addresses could use `/root/component/property` instead of `/root/component.property`, that would pair nicely with #115 .

**Comment by neilcsmith-net** [comment]
This should now be implementable in a custom component quite easily.  Can have a look at what exactly is required if you still need this?  Blanket exposing properties over OSC could be a security concern, so this will have to remain a per-user per-project choice.
