### ISSUE TITLE
ability to clone components instead of forking them

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#118]
Lets say I have some components I use regularly, like my tap tempo. I really wish I could clone that component instead of forking it, so if I update the component all instances would update.

**Comment by neilcsmith-net** [comment]
Clone inside one project or across many? 

Being able to clone / extend components in the same patch is being looked at, although not easy to figure the right approach. Across patches or projects would require a different approach.

It is possible to have a custom component that has an editable String that updates other components. Think we discussed this once?

**Comment by maxdee** [comment]
I was thinking clone inside one project. Although across many projects would be useful, but also maybe problematic. I think I could just do with copy pasting for that, as I would only have to update one of the components in each project.

**Comment by neilcsmith-net** [comment]
One project / multiple projects is different to one _patch_ (Root) though. There are lots of potential workarounds / UI improvements over the existing functionality.  But to make this work in the ideal way within one patch, PraxisCORE needs to support an atomic swap of all respective nodes, so that you don't end up with clones or sub-nodes having different code in any particular "frame".

**Comment by neilcsmith-net** [comment]
Working out a different approach to this, which will be based on #117 - adding a `.prototype` property which will allow for a `CodeDelegate` class in `SHARED` to act as the supertype of the component - allowing for components to both be a complete clone or override parts of the behaviour. Also will need UI support to turn an existing component into a prototype.

**Comment by neilcsmith-net** [comment]
Support for this, as outlined in previous comment, has been merged and will be in v5.5.
