### ISSUE TITLE
Support comments in graph editor

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#12]
Would be helpful to be able to add comments in patches.

**Comment by neilcsmith-net** [comment]
I assume you mean comments embedded within the patch and attached to specific locations / components?  I'd like to get this in, but am a bit wary of how it will interact with graph zooming.

**Comment by maxdee** [comment]
Components seem to scale well, the comments could be similar, but just a text box that does not look like a component. Been thinking about color coded components too...

**Comment by neilcsmith-net** [comment]
Unfortunately, there's no multi-line text component in the visual library used for the graph though!  You can embed Swing components but that doesn't work well with zooming.

One day this might get re-written with JavaFX.

**Comment by neilcsmith-net** [comment]
Opened #16 to track component colouring.

Would the ability to attach comments to specific components cover your use case?  Trying to work out the best way to implement this and save comments into the patch file format.  The easiest way would only allow for a single comment per component, and would link comment deletion to component deletion.

**Comment by maxdee** [comment]
I think it would be beneficial. When sharing projects it would be great to
attach comments to components. "This component does this because..."

**Comment by neilcsmith-net** [comment]
Yes, absolutely understand the use case!  I've wanted this myself for a while.

It's more whether only allowing a single comment per component, and not allowing an arbitrary number of comments anywhere within the patch, is too much of a compromise?

**Comment by maxdee** [comment]
Its better then no comments :P
I think it could work out and have some benefits. Its more like commenting
methods vs an object in general. Containers would also be commentable I
assume. Mouse hovering pop ups?

**Comment by neilcsmith-net** [comment]
Progress so far on comments and colouring. This allows for one fixed comment at top left (actually attached to the root or container), and one comment per component. Any thoughts?

![comments_colours](https://cloud.githubusercontent.com/assets/3975960/12728098/25c5aa7e-c918-11e5-99db-d5fffb115e43.png)

**Comment by maxdee** [comment]
Looks great, yay colors! Could component comments have a option for displaying as a mouse over pop up or constantly? Just thinking about real estate. The color coding will be extremely useful.

**Comment by neilcsmith-net** [comment]
Was planning some sort of toggle to show / hide them all.  That might not make the initial release of this though.

**Comment by maxdee** [comment]
The toggle thing sounds good too.
