### ISSUE TITLE
Error creating Capture component on Windows 10

### ISSUE THREAD

**Issue by DavidHaitch** [praxis-live/support#122]
When I build video.pxr in the Kaleidoscope example, I get the following warning:

````
Couldn't create component /video/capture1
Couldn't set property /video/capture1.source-width
Couldn't set property /video/capture1.source-height
Couldn't create connection /video/start-trigger1!out -> /video/capture1!play
Couldn't create connection /video/capture1!out -> /video/kaleidoscope!in
````

When I attempt to add a capture component to the kaleidoscope example, I get the following message:
````
Error creating component
```` 
with no further details. This also happens when adding a capture component to a newly-created empty project.

I was able to replicate this in PraxisLIVE 4.4.0 and v5.0.0-beta-2. I tried running it as Admin, too.

**Comment by DavidHaitch** [comment]
Never mind, I forgot to install GStreamer. Egg on my face, etc.

**Comment by neilcsmith-net** [comment]
No problem! It's not like you get a decent error message at the moment. :disappointed:  I need to see what we can do about providing more information about the failure to link to GStreamer here.
