### ISSUE TITLE
Jack MIDI client support

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#2]
Add support for Jack MIDI. Thanks to Salvatore Isaja this is now included in JNAJack so support should be easily done now.

Moved over from Google Code issue #31 - https://code.google.com/p/praxis/issues/detail?id=31

**Comment by nybbs2003** [comment]
when shall this be done?

**Comment by neilcsmith-net** [comment]
Unfortunately, not until v2 is ready for release (none of the work for which is actually in the issue tracker! :-\ ).  Then I'll probably have a look at improving the MIDI infrastructure to make use of the new JNAJack code.

If you're on Linux, there's a workaround in the original Google Code issue linked above, using snd-virmidi and a2jmidid.  There's an error in the text - should be modprobe snd-virmidi.
