### ISSUE TITLE
Update internal compiler to support Java 8

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#20]
Java 8 brings lots of useful new features, in particular lambdas!  This will require updating the minimum supported JRE version to 8.

Minimum JRE version is currently chosen based on the highest version available in an Ubuntu LTS release - April's 16.04 release will include OpenJDK 8.

This is a major change and so targeted for v3.

**Comment by maxdee** [comment]
Any work around to run on 16.04?
Just got my new laptop and really excited to Praxis LIVE with a good graphics card.

**Comment by neilcsmith-net** [comment]
Huh? It should be working fine on Ubuntu 16.04 with OpenJDK 8, just not supporting Java 8 features yet.  If it's not running please add some info to #32 Thanks!
