### ISSUE TITLE
Kaleidoscope example vertex shader problem in OSX

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#25]
As requested I tested the Kaleidoscope example on OSX. 
 * Late 2014 macmini
 * 3GHz intel i7
 * intel iris 1536mb graphics
 * Yosemite 10.10.3

[kaleidoscope_output_video.txt](https://github.com/praxis-live/support/files/178132/kaleidoscope_output_video.txt)

[kaleidoscope_ide_log.txt](https://github.com/praxis-live/support/files/178136/kaleidoscope_ide_log.txt)

**Comment by maxdee** [comment]
There seem to be the same problem with Smoky 3D example.

**Comment by neilcsmith-net** [comment]
Great, thanks! That I hope is with v2.2? Can you try v2.3 (released today)
and check it's fixed?

Many thanks, Neil

Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

**Comment by maxdee** [comment]
Yes! Both work with the update.

**Comment by maxdee** [comment]
There was a "2.3" on the start page of the older version where it failed.

![screen shot 2016-03-17 at 11 39 14 am](https://cloud.githubusercontent.com/assets/1138961/13851605/39546586-ec35-11e5-93b7-a19256ac50d2.png)

**Comment by neilcsmith-net** [comment]
That's deliberate, but I can see how it's potentially confusing. The start
page is loaded from the website, so it's meant to be a way of letting
people know what's in the latest version.

Maybe needs to tell you what version you're running as well!

Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

**Comment by neilcsmith-net** [comment]
Closing this, but I'll look at rewording the start page html file and adding in release dates.
