### ISSUE TITLE
Problem opening/running roots in 2.3

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#26]
Weird problem :S
Project with a video patch, a gui and osc bindings. When I open it and select my video root and click the run button, it only runs the video root and then when I select the osc root the build and run buttons are greyed out. Things do render, but there is no patching view. Also it wont quit as it is stuck on executing. These things can all be seen in the screenshot.

But if I restart and select the `OSCin.pxr` root first and build it, it starts the other roots as well, but still no patching view for the video root. But it closes properly.

[v2_3_video_patch_bug.txt](https://github.com/praxis-live/support/files/178239/v2_3_video_patch_bug.txt)

![root_bugs](https://cloud.githubusercontent.com/assets/1138961/13852739/e9471f48-ec39-11e5-8223-7bd98e9cac69.png)

**Comment by neilcsmith-net** [comment]
OK, on it.  I made a last minute bug fix this morning which introduced this one instead! :frowning:

**Comment by maxdee** [comment]
Is there a deb package I can test / start using?

**Comment by neilcsmith-net** [comment]
There will be in about 20min!

On 17 March 2016 at 17:45, maxdee <notifications@github.com> wrote:

> Is there a deb package I can test / start using?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/praxis-live/support/issues/26#issuecomment-197996382>
>



-- 
Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

Praxis LIVE - hybrid visual IDE for creative coding - www.praxislive.org
Digital Prisoners - interactive spaces and projections -
www.digitalprisoners.co.uk

**Comment by neilcsmith-net** [comment]
https://github.com/praxis-live/praxis-live/releases/tag/v2.3.1

Now to fix up the website links.

On 17 March 2016 at 17:49, Neil C Smith <neilcsmith.net@googlemail.com>
wrote:

> There will be in about 20min!
>
> On 17 March 2016 at 17:45, maxdee <notifications@github.com> wrote:
>
>> Is there a deb package I can test / start using?
>>
>> —
>> You are receiving this because you modified the open/close state.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/praxis-live/support/issues/26#issuecomment-197996382>
>>
>
>
>
> --
> Neil C Smith
> Artist : Technologist : Adviser
> http://neilcsmith.net
>
> Praxis LIVE - hybrid visual IDE for creative coding - www.praxislive.org
> Digital Prisoners - interactive spaces and projections -
> www.digitalprisoners.co.uk
>



-- 
Neil C Smith
Artist : Technologist : Adviser
http://neilcsmith.net

Praxis LIVE - hybrid visual IDE for creative coding - www.praxislive.org
Digital Prisoners - interactive spaces and projections -
www.digitalprisoners.co.uk

**Comment by maxdee** [comment]
Great! 
![screenshot - 03172016 - 02 54 44 pm](https://cloud.githubusercontent.com/assets/1138961/13857989/caccd198-ec52-11e5-859a-a4eca14deafa.png)
