### ISSUE TITLE
ctrl-/ does not comment out line in .frag file

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#28]
A small but slightly annoying bug.

**Comment by neilcsmith-net** [comment]
Yes, a known annoyance - it's not implemented in the GLSL NetBeans module I'm using.  Will check upstream, but likely will fork the code to implement.

The rectangle selection mode may be somewhat useful as a workaround (`CTRL-SHIFT-R`)? Put the cursor at the start of the block you want to comment out, `SHIFT-DOWN` to the end line, and then type or delete `//`.

 Incidentally, I never knew `CTRL-/` worked :smile: - I always use `CTRL-SHIFT-C`.

**Comment by maxdee** [comment]
Yeah that's what I thought.

**Comment by neilcsmith-net** [comment]
Looks like this is a one-liner so going to see if I can get this into an upcoming bug-fix release (v2.3.2).

**Comment by neilcsmith-net** [comment]
Added in to v2.3.2 out now.
