### ISSUE TITLE
Cant maximise patching area in 2.3.1 

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#29]
Before 2.3.1 double clicking on the tab of a patching or coding area would maximize its screen space by collapsing other elements. Is this related to Praxis LIVE or netbeans? can it be re-enabled?

**Comment by neilcsmith-net** [comment]
Nothing changed there and still working for me (not that I use it - I just minimize everything to the side all the time).  Does the maximize option in the popup menu on the tab work?

If not, recommend using `Window | Reset windows`

**Comment by maxdee** [comment]
The reset window thing fixed it, thanks!

**Comment by neilcsmith-net** [comment]
No problem!  Occasionally the windows settings in Praxis LIVE (and NetBeans) can get a little confused. :confused:
