### ISSUE TITLE
video:gl:p3d adds alpha to opaque surfaces

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#31]
The `video:gl:p3d` component incorrectly adds transparency to opaque surfaces because it renders output using `REPLACE`. Noticed while working with a sketch by @maxdee Should be fixed as a bug, however likely to break rendering in some projects relying on this, so leaving until v3.0.

**Comment by maxdee** [comment]
Was it with the blue moving 3D grid? I noticed different behaviors on
different hardware.

**Comment by neilcsmith-net** [comment]
Yes, although you shouldn't have seen different behaviour on different hardware because of this - that might be something else! :confused: 

All surfaces should be opaque by default, unless you add in a `video:composite` and set the `force-alpha` property. Sometimes you want a clear image to be black and sometimes you want it to be transparent.
