### ISSUE TITLE
Can't install on Ubuntu 16.04

### ISSUE THREAD

**Issue by lotelx** [praxis-live/support#32]
I try to install with last version of ubuntu but I can't:
Dependency errors, I have installed openjdk-9-jre.

sudo dpkg -i praxis-live_2.3.2-1_all.deb 
Seleccionando el paquete praxis-live previamente no seleccionado.
(Leyendo la base de datos ... 227491 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar praxis-live_2.3.2-1_all.deb ...
Desempaquetando praxis-live (2:2.3.2-1) ...
dpkg: problemas de dependencias impiden la configuración de praxis-live:
 praxis-live depende de openjdk-7-jre | java7-jre; sin embargo:
  El paquete `openjdk-7-jre' no está instalado.
  El paquete `java7-jre' no está instalado.

dpkg: error al procesar el paquete praxis-live (--install):
 problemas de dependencias - se deja sin configurar

**Comment by neilcsmith-net** [comment]
Thanks for the report.  There was a similar report on the mailing list a few days ago.  I'll look at making a new package with revised dependencies to include openjdk-8-jre

Note that Praxis LIVE will not run with openjdk-9. Install openjdk-8-jre and you should be able to get it to run.

**Comment by neilcsmith-net** [comment]
I've updated the deb package for this version. Please let me know if it fixes the issue, thanks.

NB. unless you have a particular need for openjdk-9-jre, uninstall it, or else at least make sure that your default jre is openjdk-8.

**Comment by maxdee** [comment]
Running `praxis_live` I get this error on 16.04
`OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release`
I rebooted, tried again, praxis_live started, then closed, then I would get the same message and nothing.
java -version : 
`openjdk version "1.8.0_91"
OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-0ubuntu4~16.04.1-b14)
OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)`

**Comment by neilcsmith-net** [comment]
That message should be OK, but you could try removing `-J-Xincgc` from `/usr/lib/praxis-live/etc/praxis_live.conf`

Could you check / attach the `~/.praxis/var/log/messages.log` file.

I'll be updating to 16.04 at some point, but not until after June! :smile:

**Comment by neilcsmith-net** [comment]
PS. I have the same version of OpenJDK 8 installed via ppa on 14.04, though hadn't tried the last release with it until just now.  It's working OK, so it's possibly something specific to Ubuntu 16.04.

PPS. Just to double check, what (if anything) does `javac -version` give you?

**Comment by maxdee** [comment]
Here is the log
[maxdee_1604_messages_log.txt](https://github.com/praxis-live/support/files/287073/maxdee_1604_messages_log.txt)

and here is `javac -version`
`javac 1.8.0_91`

**Comment by maxdee** [comment]
When I removed `-J-Xincgc` I got nothing :S 
Added it back and got the incremental CMS error.

**Comment by neilcsmith-net** [comment]
OK, nothing obvious in the logs at all - almost identical to mine (must stop all those WARNING messages!).  I'm stumped on this, and have had some reports of it working OK too :confused: 

Guess only other thing I can think of is, do you get a hs_err_pid<pid>.log file generated anywhere or a heap dump in the ~/.praxis/var/log folder?  Can you run a project using the terminal `praxis <project-folder>`?

Oh, and do you get as far as the splash screen or does it bail out before then?

**Comment by maxdee** [comment]
See edit above

**Comment by neilcsmith-net** [comment]
haha - I'm trying to write a conference talk here you know! :grinning: (actually, procrastinating)

Praxis LIVE inherits the single instance model from NetBeans.  If you try and start it while it's already running (assuming you don't pass in a different user directory) it will pass along the command line arguments to the running instance and gracefully exit.  "Gracefully" as in, I can't be bothered to tell you!

**Comment by neilcsmith-net** [comment]
btw - as it seems to be working for you, and I've had no further feedback from @lotelx I'll close this. Hopefully all sorted!
