### ISSUE TITLE
Feature request - Spout/Syphon support

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#33]
Could it be possible to implement Spout/Syphon as video output components?
There is Processing libraries for both. As much as I <3 Linux, we lack such texture sharing system. Spout/Syphon video input could be neat also.
Can help testing on OSX and Windows soon.

**Comment by neilcsmith-net** [comment]
Yes!  Just how to implement will need a little discussion.  I'm thinking of extending `video:capture` to support sources other than GStreamer, and adding a `video:send` with option for sending images (textures) to GStreamer, Syphon, Spout, etc. That could also allow for saving a video file through GStreamer ... eventually!

**Comment by maxdee** [comment]
Sounds great!

**Comment by neilcsmith-net** [comment]
Looking at this again - let's be stupidly optimistic and add a 3.1 milestone! :smile:

However, as these will be GL-specific components, then at least in the short term should be under GL category - eg. `video:gl:send` and `video:gl:receive` Not trying to make them too generic should make this easier - support for saving videos, etc. through GStreamer can be done as a separate task.

**Comment by neilcsmith-net** [comment]
Why is nothing ever simple?! :angry: Syphon (and Processing Syphon) doesn't currently support the OpenGL 3.1+ profile used in Praxis LIVE.  Need to provide a way to specify an alternative profile, and implement workarounds for anything unsupported, as per #49
