### ISSUE TITLE
video patch broken

### ISSUE THREAD

**Issue by diramazioni** [praxis-live/support#40]
I've just downloaded Praxis LIVE and I'm very exited to try it out for mixing videos, unfortunately the video patch it's not building and other examples too! Do you know when they will be usable?
Really looking forward to try it out, keep up the great work!

**Comment by neilcsmith-net** [comment]
Thanks!  Video should be usable already. However, have you followed the instructions about installing the GStreamer framework?

http://praxis-live.readthedocs.io/en/latest/installation/

Direct links to the GStreamer installers are on the Start Page and on the release notes at https://github.com/praxis-live/praxis-live/releases

Also make sure to restart the hub (red circular arrow) in-between running all examples.

If that still doesn't work, make sure the location of the GStreamer library in the preferences matches where it's installed.  If that still doesn't work, let me know what OS you're on and save/copy and attach the contents of `View | IDE log`

Let me know how you get on. Best wishes, Neil

**Comment by diramazioni** [comment]
I got it working (yes the issue was the hub once restarted all ok) and the mixing as well with x-fader !!! Incredible almost unbelievable having such a modular system is a dream coming true!
Is it possible to have the keyboard triggering the start-trigger? How can I chain several videos and mix them with another?

**Comment by neilcsmith-net** [comment]
Hi,

You can build a custom UI, or use MIDI or OSC to trigger the play button.  There is currently no support for mouse and keyboard events in the video window - it's currently in development though!

The other thing you can do is connect the `ready` port to the `play` port which will trigger playback as soon as the video file is changed.

Not sure what you mean by chaining?  You can use a `core:array:iterator` to feed a `video:player` with files, although there's currently not a signal for end-of-file.

Best thing for general support is to sign up to the mailing list at http://groups.google.com/d/forum/praxis-live  GitHub issues aren't great for that.

Glad you're enjoying Praxis LIVE.

Best wishes, Neil
