### ISSUE TITLE
open container on double click

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#44]
Since there is no longer any container:property components, double clicking a container could perhaps open it? Otherwise I do miss the container:property.

**Comment by neilcsmith-net** [comment]
I am still looking at an option for proxying any controls on containers, so this is why this change hasn't been made. This should happen during 3.x sometime.  However, I have considered whether to allow for `SHIFT-double-click` to open containers, as well as open code for editing - thoughts?

`core:container:property` is deprecated, but will still be in there until we reach 4.x.  If you _really_ miss it :smile:, switch on the option to show deprecated components under `Tools / Options / Core / Components`.

**Comment by maxdee** [comment]
The shift double click idea sounds great.
