### ISSUE TITLE
video:composite force-alpha

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#45]
Im having some trouble with video:composite, yesterday I got it to do what I want, combining 3D render with a background render, having the 3D stuff in front of the background, keying out the black. I carfully noted the parameters, background in `in` 3D stuff in `src` `force-alpha` enabled and `mode Normal`. Now today it does not work ? :spider: Tried on my two machines, intel and nvidia gxf. 
I will email you a patch.

**Comment by maxdee** [comment]
Now it works again, things done since not working, switched inputs (p2d to a p3d), perhaps images coming p2d are treated differently then p3d? I duplicate composite component was deleted, which things worked again very shortly after.

**Comment by maxdee** [comment]
Great, `background(0,0)` helps, and noted about the @Inject, I will use it more.

**Comment by neilcsmith-net** [comment]
Note that I said you never need to call `background(0,0)`! :smile: Just remove it. The only reason you'd ever want to use a background call is if you need a tinted or semi-transparent background.

I'll close this.
