### ISSUE TITLE
Add support for third-party libraries

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#47]
It should be possible for the user to add additional Java (and possibly Processing) libraries to a project.

Points to address -

- Support JAR, source or both?
- Library code needs to be available in three classpaths, possibly on different machines- running code, compiler and code editor completion.
- Should libraries be defined at a component or container/root level?
- Support classloader caching to make sure components don't see the same class from multiple classloaders (effectively not the same class!)
- How to handle library changes in already compiled component code?  Track library usage?  How?

**Comment by neilcsmith-net** [comment]
OK, decided to handle this instead on a per-hub basis, and so for many uses per-project. New `add-lib` and `add-libs` scripting commands added to default code services, allows extending the classpath used for the compiler and code loading services. Also improved behaviour of file commands like `file-list` to support globs.

Currently working in CORE (although not tested over a network). Work required to add support in projects and code editing classpath in the IDE.

Planning a hidden libraries folder inside `config`. Script line at top of main project (pxp) file will call

`add-libs [file-list "config/libs/*.jar"]`

**Comment by y8** [comment]
Can you please add a quick example of how component libraries can be done? Now I’m exporting them to pgx files and then just dropping them to the scene. But it’s quite painful to update them  afterwards: you need to manually recreate all of them.

**Comment by neilcsmith-net** [comment]
This issue is actually not related I think?  This is about being able to add Java libraries (JAR files) to projects.

With the .pxg files this is deliberate behaviour in that working code in a project shouldn't change based on changes to the .pxg file.  At least, by default.  They are like copying and pasting a fragment of code - in fact they work the same. 

Maybe a UI for updating would be useful?  But it should be something you have to opt-in to.  And at the moment there is no reference to the .pxg file stored in the project (unless you happened to save it there which some people seem to?).  A reference would need to be added, and a decision made on whether to update all properties or just the code.

This conversation might be better on https://groups.google.com/forum/#!forum/praxis-live or one of the new Gitter rooms at https://gitter.im/praxis-live
