### ISSUE TITLE
praxislive allways crash on mac os sierra

### ISSUE THREAD

**Issue by felart** [praxis-live/support#48]
Hi, praxislive seems great but it allways crash when application is launched.

Editor is displayed then praxislive crash. Tested on new macbook pro 2016 with radium 460 and sierra 10.12.2.

**Comment by neilcsmith-net** [comment]
Hi! Thanks for the feedback. Sorry to hear you're having difficulties.  I'm currently testing OSX using El Capitan.

Could you let me know -

- What Java version have you installed?
- Is there any error message?
- If you can find it, there should be a log file in the user directory.  IIRC on OSX this will be in `{HOME}/Library/Application Support/praxislive3/var/log/` - can you attempt to launch the application and then attach the latest log messages to this issue?

Thanks, Neil

**Comment by felart** [comment]
Hi,

My release is java 7 update 9.

[messages crash.txt](https://github.com/praxis-live/support/files/680727/messages.crash.txt)

thanks.

**Comment by neilcsmith-net** [comment]
Hi,

Yes, Praxis LIVE requires Java 8.  I didn't even realise Java 7 was still available for OSX.  At some point there will likely be a Praxis LIVE with included JVM - this causes too many issues.

Hopefully you closing this means you're all up and working now?

Best wishes, Neil
