### ISSUE TITLE
GLSL HSV color manipulation?

### ISSUE THREAD

**Issue by unfa** [praxis-live/support#53]
Is there a shader filter that'd allow me to perform color manipulation in the HSV space?

**Comment by neilcsmith-net** [comment]
There wasn't!  Try the attached.  What do you think?

[hsv.zip](https://github.com/praxis-live/support/files/1437597/hsv.zip)

**Comment by unfa** [comment]
Fantastic! This is exacly what I needed! Could this be shipped with PraxisLIVE? It's so incredibly useful along with the blur one.

**Comment by neilcsmith-net** [comment]
I'll add it to the custom components repo for now.  I'm working on some tools for automatic importing of that repo into the palette.

**Comment by unfa** [comment]
I learned how to use a timer, animate and random to make some slowly morphing color changes with this HSV component. Just want my visuals needed :)

**Comment by unfa** [comment]
Here's what I have created so far.
If you feed some sound to it, it'll start showing things, otherwise it'll be completely black.
[PraxisLIVE.zip](https://github.com/praxis-live/support/files/1439454/PraxisLIVE.zip)

I'm really happy that PraxisLIVE does this for me, as it'll greatly enhance my DJ performance :)
BTW: I didn't get JACK audio ports when running with `praxis` command, without the GUI, but that's not a big problem, I'll load the GUI too and just have it on a different display, minimized.

**Comment by neilcsmith-net** [comment]
@unfa thanks for sharing that - only just realised you'd shared the project :confused: Looks great, and like you're definitely getting the hang of how to use Praxis LIVE! :smile:  Did you get any stills / video of it in action?  Would love to share.

One of the gains wasn't connected to output - was that deliberate?  You also don't need the .pxg files in the project btw - their contents are stored in the video patch file.

If you can reproduce the JACK ports issue with the `praxis` CLI launcher, please open an issue - that should work fine, and have used it on a Pi recently.
