### ISSUE TITLE
GLSL Gaussian Blur shader?

### ISSUE THREAD

**Issue by unfa** [praxis-live/support#54]
The integrated video:fx:blur is not GPU accelerated (but it works in the Software rendering mode).
I guess most people doing live visuals have GLSL capable hardware to run it on.
it also looks rather crusty, two passes deliver a bit smoother results, but still far from perfect.

Is there a GLSL Gausian Blur component somewhere to use with PraxisLIVE?
Would it be a good idea to include it with the PXG package available on the main site?
Maybe even shipping it with the base PraxisLIVE package?

I tried using some exisiting fragment shaders, but I was unable to get any of them to work with PraxisLIVE - my knowlege of GLSL is very limited.

**Comment by neilcsmith-net** [comment]
The `video:fx:blur` is a fast software box blur.  It's more useful for doing image analysis than output.  It would be nice to get a gaussian blur in there.  At the moment, this is slightly limited as the existing shader components can't support multiple passes, although you could chain them.  Have you a link to the one your were trying?

**Comment by neilcsmith-net** [comment]
This is based on one from the Processing forum.  Not sure it's working quite as expected?!

[blur.zip](https://github.com/praxis-live/support/files/1437885/blur.zip)

**Comment by unfa** [comment]
I see.
I was looking also at this one:
https://github.com/Jam3/glsl-fast-gaussian-blur/issues
