### ISSUE TITLE
Hotkey to toggle connect component node to output temporarily

### ISSUE THREAD

**Issue by unfa** [praxis-live/support#55]
I miss a function to quickly connect the last selected component to output.
A hotkey would be great fro this. Hitting it again should restore the previous state.
This way users could quickly preview their data mid-stream, making it easier to tweak and understand the processing taking place.

What do you think?

**Comment by neilcsmith-net** [comment]
Not sure if it covers everything you're thinking of, but check out the release notes for v3.2. https://github.com/praxis-live/praxis-live/releases/tag/v3.2.0 This covers keyboard control of the graph editor.  It hasn't made it into the docs yet! :disappointed:
