### ISSUE TITLE
Ability to copy&paste components in editor view

### ISSUE THREAD

**Issue by agajdosi** [praxis-live/support#56]
First of all, thank you for wonderful project.

I have discovered Praxis Live recently and during my first try-outs I have find myself trying to copy-paste components in editor view. If somebody wants to copy the default component, then it just slows her down with the must to find the component in Palette. However if one edited the component, for example created a `double-osc` then the process is much slower to duplicate it.

Would be nice if one could just do `ctrl+c`+`ctrl+v` or just `ctrl+d`.

**Comment by neilcsmith-net** [comment]
Thanks for the comments - glad you're enjoying using it! 😄 

Copy & paste is supported. Just make sure you wait a second for the progress bar at the bottom before pasting - copy has to sync up to the component.  `ctrl-d` for duplicate is a good idea!  I'll think about how to add this.

You don't need to use the palette btw - documentation is a little behind implementation here!  You can right-click and use the `Add` menu.  You can also type `@` and start typing the component you want -
 in the release notes for v3.2 (but not yet in the docs) https://github.com/praxis-live/praxis-live/releases

**Comment by agajdosi** [comment]
@neilcsmith-net Thanks for reply. I will try the copy+paste it tomorrow, I must missed that.

 I have noticed the docs are behind a little bit, if I find something I could fix I will let you know. Would like to contribute something back :smile:

**Comment by neilcsmith-net** [comment]
@agajdosi all contributions gratefully received! 😁 Pull request to the docs, examples or custom components repos all very welcome.  The wiki should also be open on here if you have any ideas about what might be useful - empty at the moment.
