### ISSUE TITLE
Cant close output window if renderer not supported by hardware

### ISSUE THREAD

**Issue by maxdee** [praxis-live/support#59]
Hello, slight little bug. If I make a video patch and set renderer to `OpenGL:GL4` and then run it on hardware which does not support it, the output window stays open frozen. Its not a big deal as I can force quit and restart to set the appropriate renderer, just thought if you see something say something :) also hello from across the channel!

**Comment by maxdee** [comment]
Also when its in this frozen open state, once you stopped the video patch you cannot start it again with different profile, application needs to be closed.

**Comment by neilcsmith-net** [comment]
Hi! Thanks for reporting this.  I think it's partly related to another bug I've found with testing the third-party libs support - exceptions being thrown at certain times causing a hanging root.  However, the output window staying open on error may also be an upstream Processing bug - will test and see if I can get a workaround in the next release.

**Comment by neilcsmith-net** [comment]
Think I've worked around the upstream issues (not a bug as such, just Processing expects the VM to be shutdown on errors so doesn't clean up properly).  "Unfortunately" my updated drivers now support GL4 so I can't test this exact problem, but hopefully fixed in the coming v3.4 release.

**Comment by maxdee** [comment]
Let me know if you want me to test!

**Comment by neilcsmith-net** [comment]
Thanks - up at https://github.com/praxis-live/praxis-live/releases/tag/v3.4.0-rc1

(now to test libs support across hubs! :smile:)

**Comment by maxdee** [comment]
Tested, it works!

**Comment by neilcsmith-net** [comment]
Cool, thanks! :+1:  Just found a renderer issue with the Pi to fix and will hopefully release tomorrow.
