### ISSUE TITLE
Praxis LIVE crashes at boot up with Java 9

### ISSUE THREAD

**Issue by cjdg** [praxis-live/support#65]
Praxis crashes on startup

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fe2d23a0009, pid=30636, tid=30671
#
# JRE version: OpenJDK Runtime Environment (9.0) (build 9-internal+0-2016-04-14-195246.buildd.src)
# Java VM: OpenJDK 64-Bit Server VM (9-internal+0-2016-04-14-195246.buildd.src, mixed mode, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# C  [libjava.so+0x1d009]  JNU_GetEnv+0x19
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/Descargas/core.30636)
#
# An error report file with more information is saved as:
# /home/Descargas/hs_err_pid30636.log
[thread 30660 also had an error]
[thread 30659 also had an error]
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
/usr/lib/praxis-live/bin/../platform/lib/nbexec: línea 470: 30636 Abortado                (`core' generado) "/usr/lib/jvm/java-9-openjdk-amd64/bin/java" -Djdk.home="/usr/lib/jvm/java-9-openjdk-amd64" -classpath "/usr/lib/praxis-live/platform/lib/boot.jar:/usr/lib/praxis-live/platform/lib/org-openide-modules.jar:/usr/lib/praxis-live/platform/lib/org-openide-util.jar:/usr/lib/praxis-live/platform/lib/org-openide-util-lookup.jar:/usr/lib/praxis-live/platform/lib/org-openide-util-ui.jar:/usr/lib/praxis-live/platform/lib/locale/boot_ja.jar:/usr/lib/praxis-live/platform/lib/locale/boot_pt_BR.jar:/usr/lib/praxis-live/platform/lib/locale/boot_ru.jar:/usr/lib/praxis-live/platform/lib/locale/boot_zh_CN.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-modules_ja.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-modules_pt_BR.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-modules_ru.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-modules_zh_CN.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util_ja.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-lookup_ja.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-lookup_pt_BR.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-lookup_ru.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-lookup_zh_CN.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util_pt_BR.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util_ru.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-ui_ja.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-ui_pt_BR.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-ui_ru.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util-ui_zh_CN.jar:/usr/lib/praxis-live/platform/lib/locale/org-openide-util_zh_CN.jar" -Dnetbeans.dirs="/usr/lib/praxis-live/praxis_live:/usr/lib/praxis-live/praxis:/usr/lib/praxis-live/extide:/usr/lib/praxis-live/ide:/usr/lib/praxis-live/java:" -Dnetbeans.home="/usr/lib/praxis-live/platform" '-Dpraxis.version=3.5.0' '-Dsun.java2d.d3d=false' '-Dfile.encoding=UTF-8' -DaddExports:java.desktop/sun.awt=ALL-UNNAMED -DaddExports:java.base/jdk.internal.jrtfs=ALL-UNNAMED -DaddExports:java.desktop/java.awt.peer=ALL-UNNAMED -DaddExports:java.desktop/com.sun.beans.editors=ALL-UNNAMED -DaddExports:java.desktop/sun.awt.im=ALL-UNNAMED -DaddExports:java.desktop/com.sun.java.swing.plaf.gtk=ALL-UNNAMED -DaddExports:java.management/sun.management=ALL-UNNAMED -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath="/home//.praxislive3/var/log/heapdump.hprof" org.netbeans.Main --cachedir "/home/.praxislive3/var/cache" --userdir "/home//.praxislive3" "--branding" "praxis_live" 0<&0

**Comment by neilcsmith-net** [comment]
Thanks for the report.

Firstly, Praxis LIVE will only work with Java / OpenJDK 8 at the moment - there is a potential workaround but it will be properly fixed in v4 - requires update to Apache NetBeans which isn't released yet.

Secondly, Java 9 was released in Sept 2017.  You seem to be running a really early build of OpenJDK 9 from April 2016?  I would uninstall that - it's likely to break in lots of other ways.

**Comment by neilcsmith-net** [comment]
Appears to be this - https://bugs.openjdk.java.net/browse/JDK-8173626
