### ISSUE TITLE
OSX 10.6.8 not running Praxis Live

### ISSUE THREAD

**Issue by carlveira** [praxis-live/support#8]
Hello, 

I'm using OSX 10.6.8 and I can't manage to run Praxis Live on it. Is this some compatibility issue? Or might the problem be some other?

Thanks, 

Carlos

**Comment by neilcsmith-net** [comment]
@carlveira can I assume you've sorted your issue?  I think Praxis LIVE won't work with OSX 10.6.8 as it requires Java 7+.  Processing 3 requires 10.8.3 and recommends 10.9 or above, so even if you get Praxis LIVE to run you may have issues with OpenGL rendering.

Unfortunately OSX is the one platform we can't directly test on, so are reliant on users for feedback.  Please do let me know how you get on.

Thanks, Neil
