### ISSUE TITLE
Excluding files or folders from Project Browser

### ISSUE THREAD

**Issue by y8** [praxis-live/support#89]
Right now Project Browser includes all the files, including `dotfiles` or `dotfolders` (`.git`, `.gitignore`, `.DS_Store` & etc). 

It would be nice to have a tool to configure patterns to exclude from Project Browser. Something that behaves like `.gitignore` will be enough.

**Comment by neilcsmith-net** [comment]
Added in the default visibility query from NetBeans.  No option to configure yet, and not sure if this wouldn't be better as a `.gitignore` like format anyway, but it's a start! :smile: Will be in 4.1.

It uses the default NetBeans regex (below). This covers `.git` and `.DS_Store`, but leaves `.gitignore` visible and editable, which I think makes most sense.

`^(CVS|SCCS|vssver.?\\.scc|#.*#|%.*%|_svn)$|~$|^\\.(git|hg|svn|cache|DS_Store)$|^Thumbs.db$`
