### ISSUE TITLE
praxis_live.app closes without error message, OSX 10.9.5

### ISSUE THREAD

**Issue by arebe** [praxis-live/support#9]
I just downloaded the latest version of Praxis Live (v2.2.0) Mac bundle. When attempting to run the app, the icon appeared in the tray for a few seconds, then the app closed with no error.

Seems to need the latest version of Java - I installed it and now the app runs. Might be cool to get some kind of error message, or add this system requirement to the docs. Thanks!

**Comment by neilcsmith-net** [comment]
Thanks for the issue report.  I assume you had no version of Java installed?  The launcher mechanism is inherited from NetBeans.  I have seen an error message when only an old version of Java is available, but not sure it can show a message without any.  I'll look into this and see if it's possible to make it a bit more friendly.

It is already mentioned in the system requirements at http://praxis-live.readthedocs.org/en/latest/installation/

**Comment by neilcsmith-net** [comment]
Closed due to lack of feedback.
