### ISSUE TITLE
Using Praxis on ubuntu 18.04

### ISSUE THREAD

**Issue by cjdg** [praxis-live/support#92]
Hi is there any way so we can use praxis on ubuntu 18.04? a script or something else? there is still a jdk 8 on this release

**Comment by neilcsmith-net** [comment]
Hi, Thanks for the report! :smile:  I don't have 18.04 installed on anything yet, but was expecting this.  PraxisLIVE won't run on Java 9 or above (until 4.1 or 4.2 - waiting on some dependencies to update).  On Windows and macOS, the installers now bundle a JDK, partly for this reason, but not the deb or zip files.

In the meantime you need to make sure you have a full Java 8 JDK installed.  There are then two options -

* From a terminal run `praxis_live --jdkhome /usr/lib/jvm/java-8-openjdk-amd64/` (assuming you're on 64-bit!)  If that works, then you can add that into the config files (`/usr/lib/praxis-live/etc/praxis_live.conf` and `/usr/lib/praxis-live/etc/praxis.conf`) - you'll see a line with `--jdkhome` commented out.

* Run `sudo update-alternatives --config javac` and set the javac from OpenJDK 8 as the default.  PraxisLIVE's launch script will look for `javac` before `java` so this shouldn't affect other applications.

Let me know how you get on.  This is a hard one to know the best approach to fix.  At the moment the deb works on Arm and amd64 - all the potential fixes means I'll need to build separately for each CPU.

**Comment by cjdg** [comment]
Thanks mate!

**Comment by cjdg** [comment]
It works!!!!

**Comment by neilcsmith-net** [comment]
4.3 will now run on Java 11 too. Closing this.  Thanks!
