### ISSUE TITLE
Port category support

### ISSUE THREAD

**Issue by neilcsmith-net** [praxis-live/support#94]
Add ability to add port categories (sub-types) allowing for different colouring of connections, warnings on connecting different categories, etc.

Start with annotation `@Config.Category` - possibility to add support based on API types later.
- [ ] Add Config.Category annotation and expose in port info
- [ ] Warn on category mismatch in IDE.
- [ ] Add categories for accepted types? / allow multiple categories?

**Comment by maxdee** [comment]
+ 1
great idea

**Comment by neilcsmith-net** [comment]
@maxdee glad you think so!  :smile:  Still, only supported as part of #73 for 4.1 - will do the rest later. You'll like #73 more I think anyway!
